// app/layout.tsx
export const metadata = {
    title: 'Next.js Layout App',
    description: 'Learning layouts with the App Router',
};
export default function RootLayout({ children }: { children:
        React.ReactNode }) {
    return (
        <html lang="en">
        <body>
        <header style={{ padding: '1rem', backgroundColor: '#eee' }}>
            <h1>My Layout</h1>
            <nav>
                <a href="/">Home</a> | <a href="/about">About</a>
            </nav>
        </header>
        <main style={{ padding: '1rem' }}>{children}</main>
        <footer style={{ padding: '1rem', backgroundColor: '#eee' }}>
            <p>© 2025 My App</p>
        </footer>
        </body>
        </html>
    );
}



/** import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
 **/
